name:                yam
version:             0.5.1
synopsis:            Yam Web
#description:
homepage:            https://github.com/leptonyu/yam#readme
license:             BSD3
author:              Daniel YU
maintainer:          Daniel YU <leptonyu@gmail.com>
copyright:           (c) 2018 Daniel YU
category:            Web
extra-source-files:
- README.md
- yam_test.yml
ghc-options: -Wall -optP-Wno-nonportable-include-path -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints -fno-warn-orphans -fno-warn-missing-signatures

dependencies:
  - base >= 4.7 && < 5
  - text
  - resourcet
  - conduit
  - persistent
  - unliftio-core
  - monad-logger
  - fast-logger
  - aeson
  - resource-pool
  - vault
  - wai
  - random
  - servant-server
  - bytestring
  - servant-swagger
  - servant-swagger-ui
  - reflection
  - warp
  - mtl
  - data-default
  - salak

library:
  source-dirs: src
  exposed-modules:
    - Yam
    - Yam.DataSource
    - Yam.Internal
  other-modules:
    - Yam.Types
    - Yam.Logger
    - Yam.Swagger
    - Yam.Trace

executables:
  yam:
    source-dirs:      demo
    main:             Main.hs
    dependencies:
      - yam
      - servant-server
      - mtl
      - time
      - persistent-sqlite
      - wai-extra

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
      - QuickCheck
      - text

default-extensions:
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DuplicateRecordFields
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonadFailDesugaring
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances
  - ViewPatterns
