name: yam-logger
version: 0.3.1
synopsis: Yam Logger
description: logger module for yam
maintainer: Daniel YU <leptonyu@gmail.com>
license: MIT
github: leptonyu/yam
category: Project
extra-source-files: README.md

dependencies:
  - base >= 4.7 && < 5
  - fast-logger
  - monad-logger
  - wai-logger
  - aeson
  - text
  - string-conversions

defaults:
  github: leptonyu/hpack-template
  ref: master
  path: defaults.yaml

library:
  source-dirs: src
  exposed-modules:
    - Yam.Logger
