name: yam-config
version: 0.3.1
synopsis: Yam Configuation
description: Configuation Loader Module for yam
maintainer: Daniel YU <leptonyu@gmail.com>
license: MIT
github: leptonyu/yam
category: Project
extra-source-files: README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - yaml
  - text
  - string-conversions
  - unordered-containers

defaults:
  github: leptonyu/hpack-template
  ref: master
  path: defaults.yaml

library:
  source-dirs: src
  exposed-modules:
    - Yam.Config
