name:                yam
version:             0.5.4
synopsis:            Yam Web
#description:
homepage:            https://github.com/leptonyu/yam/yam#readme
license:             BSD3
author:              Daniel YU
maintainer:          Daniel YU <leptonyu@gmail.com>
copyright:           (c) 2018 Daniel YU
category:            Web
extra-source-files:
- README.md
- yam_test.yml

dependencies:
  - base >= 4.7 && < 5
  - text
  - bytestring
  - aeson
  - mtl
  - unliftio-core
  - lens
  - reflection
  - data-default
  - vault
  - random
  - monad-logger
  - fast-logger
  - wai
  - warp
  - http-types
  - servant-server
  - servant-swagger
  - servant-swagger-ui
  - swagger2
  - salak

library:
  source-dirs: src
  exposed-modules:
    - Yam
    - Yam.Internal
    - Yam.Auth
  other-modules:
    - Yam.Types
    - Yam.Logger
    - Yam.Swagger
    - Yam.Trace

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
      - QuickCheck
      - text

defaults:
  local: ../defaults.yaml
