name:                yam
version:             0.5.2
synopsis:            Yam Web
#description:
homepage:            https://github.com/leptonyu/yam/yam#readme
license:             BSD3
author:              Daniel YU
maintainer:          Daniel YU <leptonyu@gmail.com>
copyright:           (c) 2018 Daniel YU
category:            Web
extra-source-files:
- README.md
- yam_test.yml

dependencies:
  - base >= 4.7 && < 5
  - text
  - bytestring
  - aeson
  - mtl
  - reflection
  - data-default
  - vault
  - random
  - monad-logger
  - fast-logger
  - wai
  - warp
  - servant-server
  - servant-swagger
  - servant-swagger-ui
  - salak

library:
  source-dirs: src
  exposed-modules:
    - Yam
    - Yam.Internal
  other-modules:
    - Yam.Types
    - Yam.Logger
    - Yam.Swagger
    - Yam.Trace

executables:
  yam:
    source-dirs:      demo
    main:             Main.hs
    dependencies:
      - yam
      - servant-server
      - mtl

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
      - QuickCheck
      - text

defaults:
  local: ../defaults.yaml